### PR TITLE
Feat/faucet kotti

### PR DESCRIPTION
**Pull request by meowsbits**
Replacing #19 b/c that had a lot of irrelevant changes mysteriously included.

PR just for developer visibility and adhoc reference. 

The idea is to enable `cmd/faucet` to play nicely with Kotti just to get a supported faucet up and running per @shanejonas idea. Eventually we can look at and discuss migrating some of the other supported chains as well.

### CODE REVIEW

**Comment by meowsbits** [comment]
http://157.230.239.163:8080/

https://stats.kotti.goerli.net/

```
RestartSec=3
TimeoutStopSec=10min
ExecStart=/bin/sh -c '/root/go/src/github.com/ethereum/go-ethereum/build/bin/faucet -loglevel=6 -kotti -network=6 -faucet.name="Kotti" -account.json=/root/.ethereum/kotti/keystore/UTC--2019-01-30T14-49-18.711193885Z--009bd67e2d46db4e2c948d89dfdc511723495e55 -account.pass=/root/kottipass.txt -faucet.amount=3 -ethport 30313 -ethstats "ETC Labs Kotti Faucet #0":g00eyface@wss://stats.kotti.goerli.net'
[Install]
WantedBy=default.target

~               
```

**Comment by meowsbits** [comment]
Seeing a heck of a lot of the logs below. Seems like not wanting to connect to peers (`"useless peer"`)...

```
May 22 17:07:33 etclabs-kotti sh[23509]: WARN [05-22|17:07:33.528] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.557] <-net.timeout
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.557]                                          msg="--- (3) pongTimeout for 06333009fc9ef3c9@51.141.15.254:30303: verifyinit -> unknown (ok)"
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.557] <-net.queryReq
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.558] <-net.timeout
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.558]                                          msg="--- (2) pongTimeout for ae8658da8d255d19@18.232.185.151:30303: verifyinit -> unknown (ok)"
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.559] <-net.timeout
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.559]                                          msg="--- (1) pongTimeout for 67913271d14f4456@157.230.239.163:30303: verifyinit -> unknown (ok)"
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.560] <-net.timeout
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.560]                                          msg="--- (0) pongTimeout for e8a786a894db053f@86.103.236.55:63384: verifyinit -> unknown (ok)"
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.560] <-net.refreshDone                        table size=0
May 22 17:07:33 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:33.563]                                          msg="seed node (age 432929h7m33.563826747s): enode://06333009fc9ef3c9e174768e495722a7f98fe7afd4660542e983005f85e556028410fd03278944f44cfe5437b1750b5e6bd1738f700fe7da3626d52010d2954c@51.141.15.254:30303"
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.563] Pinging remote node                      node=06333009fc9ef3c9
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.564] >>> nodeEvent(1) to 06333009fc9ef3c9@51.141.15.254:30303
May 22 17:07:33 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:33.564]                                          msg="seed node (age 432929h7m33.564899767s): enode://ae8658da8d255d1992c3ec6e62e11d6e1c5899aa1566504bc1ff96a0c9c8bd44838372be643342553817f5cc7d78f1c83a8093dee13d77b3b0a583c050c81940@18.232.185.151:30303"
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.565] Pinging remote node                      node=ae8658da8d255d19
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.565] >>> nodeEvent(1) to ae8658da8d255d19@18.232.185.151:30303
May 22 17:07:33 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:33.565]                                          msg="seed node (age 432929h7m33.565911153s): enode://67913271d14f445689e8310270c304d42f268428f2de7a4ac0275bea97690e021df6f549f462503ff4c7a81d9dd27288867bbfa2271477d0911378b8944fae55@157.230.239.163:30303"
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.566] Pinging remote node                      node=67913271d14f4456
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.566] >>> nodeEvent(1) to 67913271d14f4456@157.230.239.163:30303
May 22 17:07:33 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:33.566]                                          msg="seed node (age 432929h7m33.566839004s): enode://e8a786a894db053fe6886e283fc4385389ad034e04a692a26335f30b714059efd5cead0e410ecd783ce095888fdafcc21a685f13501594e969d6f5ac7ba0388c@86.103.236.55:63384"
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.566] Pinging remote node                      node=e8a786a894db053f
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.567] >>> nodeEvent(1) to e8a786a894db053f@86.103.236.55:63384
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.567] <-net.queryReq
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.567] <-net.queryReq
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.567] <-net.queryReq
May 22 17:07:33 etclabs-kotti sh[23509]: TRACE[05-22|17:07:33.567] <-net.queryReq
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.065] <-net.timeout
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.065]                                          msg="--- (3) pongTimeout for 06333009fc9ef3c9@51.141.15.254:30303: verifyinit -> unknown (ok)"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.065] <-net.queryReq
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.066] <-net.timeout
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.066]                                          msg="--- (2) pongTimeout for ae8658da8d255d19@18.232.185.151:30303: verifyinit -> unknown (ok)"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.066] <-net.timeout
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.067]                                          msg="--- (1) pongTimeout for 67913271d14f4456@157.230.239.163:30303: verifyinit -> unknown (ok)"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.068] <-net.timeout
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.068]                                          msg="--- (0) pongTimeout for e8a786a894db053f@86.103.236.55:63384: verifyinit -> unknown (ok)"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.068] <-net.refreshDone                        table size=0
May 22 17:07:34 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:34.071]                                          msg="seed node (age 432929h7m34.071923319s): enode://06333009fc9ef3c9e174768e495722a7f98fe7afd4660542e983005f85e556028410fd03278944f44cfe5437b1750b5e6bd1738f700fe7da3626d52010d2954c@51.141.15.254:30303"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.072] Pinging remote node                      node=06333009fc9ef3c9
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.072] >>> nodeEvent(1) to 06333009fc9ef3c9@51.141.15.254:30303
May 22 17:07:34 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:34.073]                                          msg="seed node (age 432929h7m34.073032232s): enode://ae8658da8d255d1992c3ec6e62e11d6e1c5899aa1566504bc1ff96a0c9c8bd44838372be643342553817f5cc7d78f1c83a8093dee13d77b3b0a583c050c81940@18.232.185.151:30303"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.073] Pinging remote node                      node=ae8658da8d255d19
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.073] >>> nodeEvent(1) to ae8658da8d255d19@18.232.185.151:30303
May 22 17:07:34 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:34.074]                                          msg="seed node (age 432929h7m34.074015058s): enode://67913271d14f445689e8310270c304d42f268428f2de7a4ac0275bea97690e021df6f549f462503ff4c7a81d9dd27288867bbfa2271477d0911378b8944fae55@157.230.239.163:30303"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.074] Pinging remote node                      node=67913271d14f4456
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.074] >>> nodeEvent(1) to 67913271d14f4456@157.230.239.163:30303
May 22 17:07:34 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:34.074]                                          msg="seed node (age 432929h7m34.074870615s): enode://e8a786a894db053fe6886e283fc4385389ad034e04a692a26335f30b714059efd5cead0e410ecd783ce095888fdafcc21a685f13501594e969d6f5ac7ba0388c@86.103.236.55:63384"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.074] Pinging remote node                      node=e8a786a894db053f
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.075] >>> nodeEvent(1) to e8a786a894db053f@86.103.236.55:63384
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.075] <-net.queryReq
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.075] <-net.queryReq
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.075] <-net.queryReq
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.075] <-net.queryReq
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.573] <-net.timeout
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.573]                                          msg="--- (3) pongTimeout for 06333009fc9ef3c9@51.141.15.254:30303: verifyinit -> unknown (ok)"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.573] <-net.queryReq
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.574] <-net.timeout
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.574]                                          msg="--- (2) pongTimeout for ae8658da8d255d19@18.232.185.151:30303: verifyinit -> unknown (ok)"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.575] <-net.timeout
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.575]                                          msg="--- (1) pongTimeout for 67913271d14f4456@157.230.239.163:30303: verifyinit -> unknown (ok)"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.575] <-net.timeout
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.575]                                          msg="--- (0) pongTimeout for e8a786a894db053f@86.103.236.55:63384: verifyinit -> unknown (ok)"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.575] <-net.refreshDone                        table size=0
May 22 17:07:34 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:34.579]                                          msg="seed node (age 432929h7m34.579239198s): enode://06333009fc9ef3c9e174768e495722a7f98fe7afd4660542e983005f85e556028410fd03278944f44cfe5437b1750b5e6bd1738f700fe7da3626d52010d2954c@51.141.15.254:30303"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.579] Pinging remote node                      node=06333009fc9ef3c9
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.579] >>> nodeEvent(1) to 06333009fc9ef3c9@51.141.15.254:30303
May 22 17:07:34 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:34.580]                                          msg="seed node (age 432929h7m34.580076482s): enode://ae8658da8d255d1992c3ec6e62e11d6e1c5899aa1566504bc1ff96a0c9c8bd44838372be643342553817f5cc7d78f1c83a8093dee13d77b3b0a583c050c81940@18.232.185.151:30303"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.580] Pinging remote node                      node=ae8658da8d255d19
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.580] >>> nodeEvent(1) to ae8658da8d255d19@18.232.185.151:30303
May 22 17:07:34 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:34.580]                                          msg="seed node (age 432929h7m34.580734088s): enode://67913271d14f445689e8310270c304d42f268428f2de7a4ac0275bea97690e021df6f549f462503ff4c7a81d9dd27288867bbfa2271477d0911378b8944fae55@157.230.239.163:30303"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.580] Pinging remote node                      node=67913271d14f4456
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.581] >>> nodeEvent(1) to 67913271d14f4456@157.230.239.163:30303
May 22 17:07:34 etclabs-kotti sh[23509]: DEBUG[05-22|17:07:34.581]                                          msg="seed node (age 432929h7m34.581289943s): enode://e8a786a894db053fe6886e283fc4385389ad034e04a692a26335f30b714059efd5cead0e410ecd783ce095888fdafcc21a685f13501594e969d6f5ac7ba0388c@86.103.236.55:63384"
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.581] Pinging remote node                      node=e8a786a894db053f
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.581] >>> nodeEvent(1) to e8a786a894db053f@86.103.236.55:63384
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.581] <-net.queryReq
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.581] <-net.queryReq
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.581] <-net.queryReq
May 22 17:07:34 etclabs-kotti sh[23509]: TRACE[05-22|17:07:34.581] <-net.queryReq
May 22 17:07:35 etclabs-kotti sh[23509]: TRACE[05-22|17:07:35.080] <-net.timeout
```

**Comment by meowsbits** [comment]
```
root@etclabs-kotti:~# journalctl -u faucet_kotti.service --since '10 minutes ago' | grep useless
May 22 17:03:10 etclabs-kotti sh[23460]: TRACE[05-22|17:03:10.624] Rejected peer                            id=e36f97ab4606a0cd addr=157.230.239.163:30303 conn=staticdial err="useless peer"
May 22 17:03:10 etclabs-kotti sh[23460]: TRACE[05-22|17:03:10.624] Setting up connection failed             addr=157.230.239.163:30303 err="useless peer"
May 22 17:03:10 etclabs-kotti sh[23460]: TRACE[05-22|17:03:10.624] Dial error                               task="staticdial e36f97ab4606a0cd 157.230.239.163:30303" err="useless peer"
May 22 17:03:10 etclabs-kotti sh[23460]: TRACE[05-22|17:03:10.831] Rejected peer                            id=e88a70f4df859857 addr=51.141.15.254:30303   conn=staticdial err="useless peer"
May 22 17:03:10 etclabs-kotti sh[23460]: TRACE[05-22|17:03:10.833] Setting up connection failed             addr=51.141.15.254:30303   err="useless peer"
May 22 17:03:10 etclabs-kotti sh[23460]: TRACE[05-22|17:03:10.833] Dial error                               task="staticdial e88a70f4df859857 51.141.15.254:30303"   err="useless peer"
May 22 17:03:41 etclabs-kotti sh[23460]: TRACE[05-22|17:03:41.132] Rejected peer                            id=e36f97ab4606a0cd addr=157.230.239.163:30303 conn=staticdial err="useless peer"
May 22 17:03:41 etclabs-kotti sh[23460]: TRACE[05-22|17:03:41.132] Setting up connection failed             addr=157.230.239.163:30303 err="useless peer"
May 22 17:03:41 etclabs-kotti sh[23460]: TRACE[05-22|17:03:41.132] Dial error                               task="staticdial e36f97ab4606a0cd 157.230.239.163:30303" err="useless peer"
May 22 17:03:41 etclabs-kotti sh[23460]: TRACE[05-22|17:03:41.341] Rejected peer                            id=e88a70f4df859857 addr=51.141.15.254:30303   conn=staticdial err="useless peer"
```

**Comment by tzdybal** [comment]
There is also repeated "pong timeout" for all bootnodes - maybe there is a network/firewall problem?

**Comment by meowsbits** [comment]
I'm guessing it's because noone's speaking `les`.

```
  peers: [{
      caps: ["eth/62", "eth/63", "par/1", "par/2", "par/3", "pip/1"],
      enode: "enode://e8a786a894db053fe6886e283fc4385389ad034e04a692a26335f30b714059efd5cead0e410ecd783ce095888fdafcc21a685f13501594e969d6f5ac7ba0388c@86.103.236.55:56682",
      id: "174ba42a46b97678a62253270db9a0dd2900e7d355828710d16fe131c2d1cf3e",
      name: "Parity-Ethereum/v2.5.0-unstable/x86_64-linux-gnu/rustc1.34.1",
      network: {
        inbound: true,
        localAddress: "157.230.239.163:30303",
        remoteAddress: "86.103.236.55:56682",
        static: false,
        trusted: false
      },
      protocols: {
        eth: {...}
      }
  }, {
      caps: ["eth/62", "eth/63"],
      enode: "enode://ae8658da8d255d1992c3ec6e62e11d6e1c5899aa1566504bc1ff96a0c9c8bd44838372be643342553817f5cc7d78f1c83a8093dee13d77b3b0a583c050c81940@35.175.107.242:30303",
      id: "5b765de8c66086573343815f26185dd79bbebbe8a9a2ae4da1f22b782e5de1ff",
      name: "Geth/v1.9.0-unstable-187e8a42/linux-amd64/go1.11.4",
      network: {
        inbound: false,
        localAddress: "157.230.239.163:35276",
        remoteAddress: "35.175.107.242:30303",
        static: false,
        trusted: false
      },
      protocols: {
        eth: {...}
      }
  }, {
      caps: ["eth/62", "eth/63", "par/1", "par/2", "par/3", "pip/1"],
      enode: "enode://db8be397c6fe92b01e5ef5841bff8a346b944f10011f6c3dd08d181d36522b2731224ad965b776a186e7dc46546a17f9d2d25d70d36a58a5078979cc02781fd6@86.103.236.55:63770",
      id: "982511c357ba30d8ab70f5918db3350259ebcf527bc98ba41ad3f7bd4682686f",
      name: "Parity-Ethereum/v2.5.0-unstable/x86_64-linux-gnu/rustc1.34.1",
      network: {
        inbound: true,
        localAddress: "157.230.239.163:30303",
        remoteAddress: "86.103.236.55:63770",
        static: false,
        trusted: false
      },
      protocols: {
        eth: {...}
      }
  }, {
      caps: ["eth/62", "eth/63", "par/1", "par/2", "par/3", "pip/1"],
      enode: "enode://06333009fc9ef3c9e174768e495722a7f98fe7afd4660542e983005f85e556028410fd03278944f44cfe5437b1750b5e6bd1738f700fe7da3626d52010d2954c@51.141.15.254:30303",
      id: "e88a70f4df8598576945662d00cdbc4a022b37be5b5a27e107ec4c709404ad23",
      name: "Parity-Ethereum/v2.5.1-beta-e0141f8-20190510/x86_64-linux-gnu/rustc1.34.1",
      network: {
        inbound: false,
        localAddress: "157.230.239.163:36670",
        remoteAddress: "51.141.15.254:30303",
        static: false,
        trusted: false
      },
      protocols: {
        eth: {...}
      }
  }],
```

**Comment by meowsbits** [comment]
Have added `--lightserv 33` to our Kotti bootnode. Seems working now.

**Comment by tzdybal** [comment]
Confirmed! My faucet also syncs right now.

**Review by tzdybal — APPROVED** [review]
LGTM

**Pull request merged**
