### PR TITLE
Track/release eth192

### PR DESCRIPTION
**Pull request by meowsbits**
updates upstream tracking thru (confusingly) [upstream@v1.9.2](https://github.com/ethereum/go-ethereum/commit/e76047e9f5499b58064bddde514dd3119a090adf) (Blue Thessia) vs. our current HEAD@master (~1.9.2)

upstream release notes/article here: https://blog.ethereum.org/2019/07/10/geth-v1-9-0/

worth noting that we've already had a large amount of the changes cited in the article above for the past few of our own releases (since we're ahead of the curve), eg. "freezing" db

notable changes so far visible to me via merge conflict resolutions:
- CheckpointOracles for les
- refactored out params gas table -> vm 
- upstream using `ExtraEIPs` and refactored some jump table stuff, but no biggies for vs. our EIP-aware factoring
- some istanbul stuff is starting to come in

wip for sanity check, code review, and testing

### CODE REVIEW

**Comment by meowsbits** [comment]
TODO:
- [x] fix - see https://github.com/etclabscore/multi-geth/pull/28/commits/ec7630d36c49a6fd97b497e9526dded2bb83d402

```
$ make test 
... 
github.com/ethereum/go-ethereum/cmd/bootnode
github.com/ethereum/go-ethereum/cmd/abigen
github.com/ethereum/go-ethereum/cmd/checkpoint-admin
github.com/ethereum/go-ethereum/signer/fourbyte
github.com/ethereum/go-ethereum/cmd/ethkey
# github.com/ethereum/go-ethereum/tests
tests/state_test_util.go:153:10: vmconfig.ExtraEips undefined (type vm.Config has no field or method ExtraEips)
github.com/ethereum/go-ethereum/cmd/evm/internal/compiler
github.com/ethereum/go-ethereum/vendor/github.com/julienschmidt/httprouter
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/ed25519
github.com/ethereum/go-ethereum/cmd/rlpdump
```

**Comment by meowsbits** [comment]
not sure why this is failing... https://travis-ci.org/etclabscore/multi-geth/jobs/577972987#L565

locally fine:
```
$ go test ./p2p/...
ok      github.com/ethereum/go-ethereum/p2p     (cached)
ok      github.com/ethereum/go-ethereum/p2p/discover    (cached)
ok      github.com/ethereum/go-ethereum/p2p/discv5      (cached)
ok      github.com/ethereum/go-ethereum/p2p/enode       (cached)
ok      github.com/ethereum/go-ethereum/p2p/enr (cached)
ok      github.com/ethereum/go-ethereum/p2p/nat (cached)
ok      github.com/ethereum/go-ethereum/p2p/netutil     (cached)
ok      github.com/ethereum/go-ethereum/p2p/simulations (cached)
ok      github.com/ethereum/go-ethereum/p2p/simulations/adapters        (cached)
?       github.com/ethereum/go-ethereum/p2p/simulations/examples        [no test files]
?       github.com/ethereum/go-ethereum/p2p/simulations/pipes   [no test files]
?       github.com/ethereum/go-ethereum/p2p/testing     [no test files]
```

looks like a bad test that's wrongly comparing error msg syntax...

**Comment by tzdybal** [comment]
I can reproduce error locally.
Looking at the code, expected error message is actually wrong (they are less detailed). We can change `!=` to `!strings.Contains`, or correct expected errors.

**Comment by tzdybal** [comment]
The same error is visible on `release/1.9` on `ethereum/go-ethereum`. The code is updated, but test are old and fragile.

**Review by tzdybal — APPROVED** [review]

**Pull request merged**
