### PR TITLE
Feat/faucet kotti

### PR DESCRIPTION
**Pull request by meowsbits**

### CODE REVIEW

**Comment by meowsbits** [comment]
Where did all of these extra commits come from?

**Comment by tzdybal** [comment]
`etclabscore:master` != `multi-geth/multi-geth:master`

I mean, master of this repository is out of date.

**Comment by meowsbits** [comment]
I thought it was up to date?? I pushed...

**Comment by meowsbits** [comment]
https://github.com/etclabscore/multi-geth/commit/d1975dfe9a1420de0335d246b6c5cc34e0e8cf46

**Pull request closed without merging**
